export const mockDetail = {
  chainId: 'tDVV',
  blockHeight: 29829520,
  id: 'a001e56fc65e0f8cccbcee3e60a2a8951d124108a6b7f0ece4d3a0b7833c1a16',
  creator: 'vQfjcuW3RbGmkcL74YY4q3BX9UcH5rmwLmbQi3PsZxg8vE9Uk',
  crowdFundingType: 'Sell at the set price',
  startTime: '2024-01-18T11:53:01Z',
  endTime: '2024-01-25T03:52:01Z',
  tokenReleaseTime: '2024-01-20T08:52:01Z',
  toRaisedAmount: '1000000000',
  crowdFundingIssueAmount: '1000000000',
  preSalePrice: '100000000',
  publicSalePrice: '200000000',
  minSubscription: '1',
  maxSubscription: '1000000000',
  listMarketInfo: '[]',
  liquidityLockProportion: 50,
  unlockTime: '2024-01-29T17:52:01Z',
  firstDistributeProportion: '100000000',
  restDistributeProportion: 0,
  totalPeriod: 1,
  additionalInfo: JSON.stringify({
    projectName: 'Citizen Conflict',
    projectSummary:
      'The mobile game immerses players in a metaverse that bridges the virtual and physical worlds, DEFY fuses hyper casual code-breaking gameplay, with real world exploration and Augmented Reality (AR) adventures.',
    projectDescription:
      'The DEFY team believes that in order to make P&E sustainable for the long term, it is critical to wrap the earning mechanics in a fun, highly engaging game which is rewarding beyond just playing to earn. Using a rich narrative and introducing novel new features into the game, DEFY is built for the long term. Furthermore, the DEFY game economy has been built to harness the creativity of the community, via the upcoming creators platform which will allow users to burn $DEFY tokens in order to forge and create new NFT game assets which may be sold via a native marketplace. By doing this, DEFY is creating a platform that has the ability to absorb and distribute value in multiple ways. Location based play and earn game DEFY fuses hyper casual code breaking gameplay, real world exploration and AR adventures The mobile game immerses players in a metaverse that bridges the virtual and physical worlds, DEFY fuses hyper casual code-breaking gameplay, with real world exploration and Augmented Reality (AR) adventures. DEFY Labs is proud to announce the completion of their US$3.5m seed round led by Animoca Brands, liveXThe Spartan Group, GameFi Ventures, BIXIN, Polygon Studios, Unanimous Capital, PathDAO andPlay It Forward DAO DEFY’s in-game economy has been designed with scale and longevity in mind. A dual currency model is combined with an extensive set of customisable tradable game assets as well as multiple active and passive earning mechanisms that can be leveraged by the players. A creators platform will be added for content creators to collaborate with DEFY and bring NFTs into Augmented Reality. DEFY intends to bring PvP into DEFY which creates huge longevity.',
    x: 'https://www.google.com/',
    telegram: 'https://www.google.com/',
    medium: 'https://www.google.com/',
    logoUrl: '',
    projectImgs: 'url1,url2',
  }),
  isCanceled: false,
  isEnableWhitelist: true,
  whitelistId: '3e205f05b2eae8833f8b10300f3d5246728dfb43d3fd249b0809ecda6492abc6',
  currentRaisedAmount: '100000000',
  currentCrowdFundingIssueAmount: 0,
  participantCount: 0,
  currentPeriod: 0,
  periodDuration: 0,
  isBurnRestToken: true,
  receivableLiquidatedDamageAmount: 0,
  lastModificationTime: undefined,
  toRaiseToken: {
    chainId: 'tDVV',
    symbol: 'ELF',
    name: 'Native Token',
    address: '7RzVGiuVWkvL4VfVHdZfQF2Tri3sgLe9U991bohHFfSRZXuGX',
    decimals: 8,
    id: 'tDVV-ELF',
  },
  crowdFundingIssueToken: {
    chainId: 'tDVV',
    symbol: 'LINHONG',
    name: 'LINHONG token',
    address: '7RzVGiuVWkvL4VfVHdZfQF2Tri3sgLe9U991bohHFfSRZXuGX',
    decimals: 8,
    id: 'tDVV-LINHONG',
  },
  investAmount: '1000',
  toClaimAmount: '1000',
  investCreateTime: '0001-01-01T00:00:00',
  createTime: '2024-01-18T11:52:04.6347416Z',
  cancelTime: undefined,
  status: 3,
  realEndTime: '2024-01-20T08:52:01Z',
  liquidatedDamageAmount: '10',
};

export const mockWhitelistInfo = {
  whitelistId: '3e205f05b2eae8833f8b10300f3d5246728dfb43d3fd249b0809ecda6492abc6',
  projectId: 'a001e56fc65e0f8cccbcee3e60a2a8951d124108a6b7f0ece4d3a0b7833c1a16',
  extraInfoIdList: {
    value: [
      {
        addressList: {
          value: [],
        },
        id: null,
      },
    ],
  },
  isAvailable: true,
  isCloneable: false,
  remark: '',
  cloneFrom: null,
  creator: 'mhgUyGhd27YaoG8wgXTbwtbAiYx7E59n5GXEkmkTFKKQTvGnB',
  manager: {
    value: ['mhgUyGhd27YaoG8wgXTbwtbAiYx7E59n5GXEkmkTFKKQTvGnB', 'vQfjcuW3RbGmkcL74YY4q3BX9UcH5rmwLmbQi3PsZxg8vE9Uk'],
  },
  strategyType: 'Basic',
  url: 'https://www.google.com/',
};

export const mockPreviewData = {
  chainId: 'tDVV',
  crowdFundingType: 'Sell at the set price',
  startTime: '2024-01-18T11:53:01Z',
  endTime: '2024-01-25T03:52:01Z',
  toRaisedAmount: '1000000000',
  crowdFundingIssueAmount: '1000000000',
  preSalePrice: '100000000',
  minSubscription: '1',
  maxSubscription: '1000000000',
  unlockTime: '2024-01-29T17:52:01Z',
  additionalInfo: {
    projectName: 'Citizen Conflict',
    projectSummary:
      'The mobile game immerses players in a metaverse that bridges the virtual and physical worlds, DEFY fuses hyper casual code-breaking gameplay, with real world exploration and Augmented Reality (AR) adventures.',
    projectDescription:
      'The DEFY team believes that in order to make P&E sustainable for the long term, it is critical to wrap the earning mechanics in a fun, highly engaging game which is rewarding beyond just playing to earn. Using a rich narrative and introducing novel new features into the game, DEFY is built for the long term. Furthermore, the DEFY game economy has been built to harness the creativity of the community, via the upcoming creators platform which will allow users to burn $DEFY tokens in order to forge and create new NFT game assets which may be sold via a native marketplace. By doing this, DEFY is creating a platform that has the ability to absorb and distribute value in multiple ways. Location based play and earn game DEFY fuses hyper casual code breaking gameplay, real world exploration and AR adventures The mobile game immerses players in a metaverse that bridges the virtual and physical worlds, DEFY fuses hyper casual code-breaking gameplay, with real world exploration and Augmented Reality (AR) adventures. DEFY Labs is proud to announce the completion of their US$3.5m seed round led by Animoca Brands, liveXThe Spartan Group, GameFi Ventures, BIXIN, Polygon Studios, Unanimous Capital, PathDAO andPlay It Forward DAO DEFY’s in-game economy has been designed with scale and longevity in mind. A dual currency model is combined with an extensive set of customisable tradable game assets as well as multiple active and passive earning mechanisms that can be leveraged by the players. A creators platform will be added for content creators to collaborate with DEFY and bring NFTs into Augmented Reality. DEFY intends to bring PvP into DEFY which creates huge longevity.',
    x: 'https://www.google.com/',
    telegram: 'https://www.google.com/',
    medium: 'https://www.google.com/',
    logoUrl: '',
    projectImgs: 'url1,url2',
  },
  isCanceled: false,
  isEnableWhitelist: true,
  whitelistId: '3e205f05b2eae8833f8b10300f3d5246728dfb43d3fd249b0809ecda6492abc6',
  currentRaisedAmount: '0',
  currentCrowdFundingIssueAmount: '0',
  receivableLiquidatedDamageAmount: '0',
  toRaiseToken: {
    chainId: 'tDVV',
    symbol: 'ELF',
    name: 'Native Token',
    address: '7RzVGiuVWkvL4VfVHdZfQF2Tri3sgLe9U991bohHFfSRZXuGX',
    decimals: 8,
    id: 'tDVV-ELF',
  },
  crowdFundingIssueToken: {
    chainId: 'tDVV',
    symbol: 'LINHONG',
    name: 'LINHONG token',
    address: '7RzVGiuVWkvL4VfVHdZfQF2Tri3sgLe9U991bohHFfSRZXuGX',
    decimals: 8,
    id: 'tDVV-LINHONG',
  },
  investAmount: '0',
  toClaimAmount: '0',
  status: 2, // UPCOMING
  isInWhitelist: false,
  whitelistInfo: {
    url: 'https://www.google.com/',
  },
};
